/**
 * Event listener template — used by `nx make:listener`.
 *
 * Context keys:
 *   name  — PascalCase class name (e.g. "UserEvents")
 *   kebab — kebab-case file name (e.g. "user-events")
 */
export default `
import { Inject, Injectable } from '@nexusts/core';
import { EventService, OnEvent } from '@nexusts/events';

/**
 * {{ name }} listener — generated by \`nx make:listener {{ name }}\`.
 *
 * Register handlers below with \`@OnEvent(pattern)\`. Pair with
 * \`scanForListeners(this, eventService)\` at boot.
 */
@Injectable()
export class {{ name }}Listener {
  @Inject(EventService.TOKEN) declare private readonly events: EventService;

  // TODO: add @OnEvent('your.event') handlers below.

  // @OnEvent('user.created')
  // async onUserCreated(payload: { userId: string; email: string }) {
  //   this.events; // unused — remove if you don't need it
  // }
}

import { scanForListeners } from '@nexusts/events';

/**
 * Bootstrap helper — call this from your main.ts (or wherever you
 * wire up the application) to register every \`@OnEvent\` handler
 * on this listener class.
 */
export async function register{{ name }}(listener: {{ name }}Listener, events: EventService) {
  return scanForListeners(listener, events);
}
`.trimStart();
