/**
 * Queue job enqueue helper template — used by `nx make:queue`.
 *
 * Context keys:
 *   name  — PascalCase class name (e.g. "SendWelcomeEmail")
 *   kebab — kebab-case file name (e.g. "send-welcome-email")
 */
export default `
import { Inject, Injectable } from '@nexusts/core';
import { QueueService } from '@nexusts/queue';
import type { {{ name }}Data } from './{{ kebab }}.worker.js';

/**
 * Helper for enqueuing \`{{ name }}\` jobs from controllers / services.
 * Generated by \`nx make:queue {{ name }}\`.
 */
@Injectable()
export class {{ name }}Job {
  @Inject(QueueService.TOKEN) declare private readonly queue: QueueService;

  /** Enqueue a single {{ name }} job. */
  async enqueue(data: {{ name }}Data, options?: {
    delaySeconds?: number;
    attempts?: number;
  }) {
    return this.queue.add('{{ name }}', data, options);
  }

  /** Enqueue many at once. */
  async enqueueBatch(items: {{ name }}Data[]) {
    return this.queue.addBatch(
      items.map((data) => ({ name: '{{ name }}', data })),
    );
  }
}
`.trimStart();
