/**
 * Queue worker template — used by `nx make:queue`.
 *
 * Context keys:
 *   name  — PascalCase class name (e.g. "SendWelcomeEmail")
 *   kebab — kebab-case file name (e.g. "send-welcome-email")
 */
export default `
import { Inject, Injectable } from '@nexusts/core';
import { QueueService, OnQueueReady } from '@nexusts/queue';

/**
 * {{ name }} worker — generated by \`nx make:queue {{ name }}\`.
 *
 * Registers a handler for the \`{{ name }}\` job name on boot.
 */
@Injectable()
export class {{ name }}Worker {
  @Inject(QueueService.TOKEN) declare private readonly queue: QueueService;

  @OnQueueReady()
  async register(): Promise<void> {
    await this.queue.process('{{ name }}', async (data, ctx) => {
      ctx.prefix; // → "[queue:{{ name }}]"
      try {
        await this.handle(data as {{ name }}Data);
        return { status: 'completed' };
      } catch (err) {
        return {
          status: 'failed',
          error: err instanceof Error ? err : new Error(String(err)),
          willRetry: ctx.attempts < 3,
        };
      }
    });
  }

  /**
   * Replace this body with your actual worker logic.
   */
  async handle(data: {{ name }}Data): Promise<void> {
    // TODO: implement
  }
}

/**
 * Typed payload for the \`{{ name }}\` job.
 */
export interface {{ name }}Data {
  // TODO: define fields
  [key: string]: unknown;
}
`.trimStart();
