/**
 * Drizzle migration template.
 *
 * Context:
 *   name        — PascalCase model name
 *   tableName   — snake_case plural table
 *   columns     — column definitions (rendered by command)
 *   timestamp   — ISO timestamp prefix used in the filename
 */

export default `
import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';

/**
 * {{ name }} — migration generated by \`nx make:migration {{ name }}\`.
 * Run with \`bunx drizzle-kit migrate\` or your migration runner.
 */
export const {{ snake }} = sqliteTable('{{ tableName }}', {
  id: integer('id').primaryKey({ autoIncrement: true }),
{{ columns }}
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});
`.trimStart();