/**
 * Generic migration header.
 *
 * Context:
 *   name        — PascalCase model name
 *   timestamp   — ISO timestamp prefix
 */

export default `
-- {{ timestamp }}_create_{{ snake }}.sql
-- Generated by \`nx make:migration {{ name }}\`.

CREATE TABLE IF NOT EXISTS {{ tableName }} (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
{{ columns }}
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);
`.trimStart();