/**
 * Validator (DTO) template — for `make:validator <Name>`.
 *
 * Generates a Zod schema with reasonable starter fields.
 */

export default `
import { z } from 'zod';

/**
 * Validation schema for {{ name }}.
 * Generated by \`nx make:validator {{ name }}\`.
 */
export const {{ name }}Schema = z.object({
  // TODO: define fields. Example:
  // name: z.string().min(1).max(100),
  // email: z.string().email().optional(),
});

export type {{ name }}Input = z.infer<typeof {{ name }}Schema>;
`.trimStart();