/**
 * Drizzle ORM model template.
 *
 * Generates a Drizzle table schema + a typed repository wrapper.
 *
 * Context:
 *   name        — PascalCase class name (e.g. "User")
 *   kebab       — kebab-case file name (e.g. "user")
 *   tableName   — snake_case plural table name (e.g. "users")
 *   columns     — newline-separated column list (rendered by command)
 */

export default `
import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';

/**
 * {{ tableName }} — generated by \`nx make:model {{ name }}\`.
 */
export const {{ snake }} = sqliteTable('{{ tableName }}', {
  id: integer('id').primaryKey({ autoIncrement: true }),
{{ columns }}
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

export type {{ name }} = typeof {{ snake }}.$inferSelect;
export type New{{ name }} = typeof {{ snake }}.$inferInsert;
`.trimStart();