/**
 * Prisma model template.
 *
 * Renders a `model Foo { ... }` block plus a typed client wrapper.
 *
 * Context:
 *   name        — PascalCase (e.g. "User")
 *   fields      — rendered field lines (name, type, optionality)
 */

export default `
/**
 * {{ name }} — generated by \`nx make:model {{ name }}\`.
 *
 * Add this block to your schema.prisma file:
 *
{{ prismaBlock }}
 */

import { PrismaClient } from '@prisma/client';
import { Inject, Injectable } from 'nexus';

@Injectable()
export class {{ name }}Repository {
  constructor(@Inject('PRISMA') private readonly prisma: PrismaClient) {}

  findAll() {
    return this.prisma.{{ camel }}.findMany();
  }

  findOne(id: number) {
    return this.prisma.{{ camel }}.findUnique({ where: { id } });
  }

  create(data: any) {
    return this.prisma.{{ camel }}.create({ data });
  }

  update(id: number, data: any) {
    return this.prisma.{{ camel }}.update({ where: { id }, data });
  }

  delete(id: number) {
    return this.prisma.{{ camel }}.delete({ where: { id } });
  }
}
`.trimStart();