/**
 * Middleware template — for `make:middleware <Name>`.
 *
 * Generates an `@Injectable()` middleware class with a `handle` method.
 */

export default `
import { Injectable } from 'nexus';
import type { Context, Next } from 'hono';

/**
 * {{ name }} middleware — generated by \`nx make:middleware {{ name }}\`.
 */
@Injectable()
export class {{ name }}Middleware {
  async handle(c: Context, next: Next): Promise<Response> {
    // TODO: pre-handler logic
    const res = await next();
    // TODO: post-handler logic
    return res;
  }
}
`.trimStart();