/**
 * `nx make:auth` — scaffold an auth module.
 *
 * Generates:
 *   - src/auth/auth.ts            — better-auth instance
 *   - src/auth/auth.module.ts     — NexusJS module (or copy if exists)
 *   - src/auth/.env.example       — BETTER_AUTH_SECRET / URL placeholders
 *   - patches nx.config.ts to include the `auth` section (with --update-config)
 *
 * Usage:
 *   nx make:auth --provider github,google --jwt --passkey
 *   nx make:auth --provider github --jwt --no-passkey
 */

import { resolve } from "node:path";
import type { Command, CommandContext } from "../core/index.js";
import {
	logger,
	flagBool,
	flagList,
	render,
	writeFile,
} from "../core/index.js";

const AUTH_INSTANCE_TEMPLATE = `/**
 * Better-auth instance — generated by \`nx make:auth\`.
 *
 * Edit \`nx.config.ts\` (\`auth\` section) instead of this file when possible.
 */
import 'reflect-metadata';
import { createAuth } from 'nexus/auth';

export const auth = createAuth({
{{^jwt}}
  jwt: { enabled: false },
{{/jwt}}
{{#jwt}}
  jwt: { enabled: true },
{{/jwt}}
{{#passkey}}
  passkey: {
    enabled: true,
    rpName: '{{ passkeyRpName }}',
    rpId:   '{{ passkeyRpId }}',
    origin: '{{ passkeyOrigin }}',
  },
{{/passkey}}
{{#providers}}
  socialProviders: {
{{#entries}}
    {{ name }}: {
      clientId:     process.env.{{ envVar }}_CLIENT_ID!,
      clientSecret: process.env.{{ envVar }}_CLIENT_SECRET!,
    },
{{/entries}}
  },
{{/providers}}
});
`;

const ENV_EXAMPLE_TEMPLATE = `# Better Auth — generated by \`nx make:auth\`.
# Generate a secret with: openssl rand -base64 32
BETTER_AUTH_SECRET=
BETTER_AUTH_URL=http://localhost:3000
{{#providers}}
{{#entries}}
{{ envVar }}_CLIENT_ID=
{{ envVar }}_CLIENT_SECRET=
{{/entries}}
{{/providers}}
`;

const MODULE_UPDATE_HINT = `import { AuthModule } from 'nexus/auth';
// In your AppModule.imports:
imports: [AuthModule.forRoot({ /* ... */ })],
`;

const KNOWN_PROVIDERS: Record<string, { env: string; label: string }> = {
	github:    { env: "GITHUB",    label: "GitHub" },
	google:    { env: "GOOGLE",    label: "Google" },
	discord:   { env: "DISCORD",   label: "Discord" },
	microsoft: { env: "MICROSOFT", label: "Microsoft" },
	apple:     { env: "APPLE",     label: "Apple" },
	facebook:  { env: "FACEBOOK",  label: "Facebook" },
	gitlab:    { env: "GITLAB",    label: "GitLab" },
	slack:     { env: "SLACK",     label: "Slack" },
	twitter:   { env: "TWITTER",   label: "Twitter" },
	spotify:   { env: "SPOTIFY",   label: "Spotify" },
	linkedin:  { env: "LINKEDIN",  label: "LinkedIn" },
};

export const makeAuthCommand: Command = {
	name: "make:auth",
	aliases: ["auth", "auth-install"],
	summary: "Scaffold the auth module",
	description:
		"Generates src/auth/auth.ts, .env.example, and an auth-ready module skeleton using better-auth.",
	examples: [
		"nx make:auth",
		"nx make:auth --provider github --jwt",
		"nx make:auth --provider github,google --jwt --passkey --rp-id example.com",
	],
	flags: [
		{ name: "provider", description: "Comma-separated OAuth providers (github, google, ...)" },
		{ name: "jwt", description: "Enable the JWT plugin (token + JWKS endpoint)" },
		{ name: "passkey", description: "Enable the passkey (WebAuthn) plugin" },
		{ name: "rp-id", description: "Passkey RP ID (defaults to 'localhost')" },
		{ name: "rp-name", description: "Passkey RP display name" },
		{ name: "origin", description: "Passkey origin (defaults to http://localhost:3000)" },
	],
	async run(ctx: CommandContext): Promise<number> {
		logger.heading("Scaffolding auth module");

		const providers = flagList(ctx.flags, "provider");
		const jwtEnabled = ctx.flags["jwt"] === true;
		const passkeyEnabled = ctx.flags["passkey"] === true;
		const rpId = (ctx.flags["rp-id"] as string | undefined) ?? "localhost";
		const rpName = (ctx.flags["rp-name"] as string | undefined) ?? "NexusJS App";
		const origin = (ctx.flags["origin"] as string | undefined) ?? "http://localhost:3000";

		const entries = providers.map((p) => {
			const known = KNOWN_PROVIDERS[p.toLowerCase()];
			return {
				name: p.toLowerCase(),
				envVar: known?.env ?? p.toUpperCase(),
			};
		});

		// 1) src/auth/auth.ts
		const authCode = render(AUTH_INSTANCE_TEMPLATE, {
			jwt: jwtEnabled,
			passkey: passkeyEnabled,
			providers: providers.length > 0,
			entries,
			passkeyRpName: rpName,
			passkeyRpId: rpId,
			passkeyOrigin: Array.isArray(origin) ? origin.join(",") : origin,
		});
		const authOut = resolve(ctx.cwd, "src/auth/auth.ts");
		if (writeFile(authOut, authCode)) {
			logger.success(`created ${authOut}`);
		} else {
			logger.warn(`skipped (exists): ${authOut}`);
		}

		// 2) .env.example
		const envCode = render(ENV_EXAMPLE_TEMPLATE, {
			providers: providers.length > 0,
			entries,
		});
		const envOut = resolve(ctx.cwd, ".env.example");
		if (writeFile(envOut, envCode, { skipIfExists: true })) {
			logger.success(`created ${envOut}`);
		} else {
			logger.warn(`skipped (exists): ${envOut}`);
		}

		// 3) Module hint
		logger.blank();
		logger.heading("Next steps");
		logger.info("1. Add a secret to .env:");
		logger.info("     BETTER_AUTH_SECRET=$(openssl rand -base64 32)");
		logger.info("2. Wire the module in AppModule:");
		logger.info(`     ${MODULE_UPDATE_HINT.trim()}`);
		if (providers.length > 0) {
			logger.info(`3. Set up OAuth credentials for: ${providers.join(", ")}`);
		}
		if (passkeyEnabled) {
			logger.info("4. Configure passkey RP ID + origin for your domain.");
		}
		logger.info("5. Run `bun --hot src/app/main.ts` to start the server.");
		logger.blank();

		return 0;
	},
};

export default makeAuthCommand;