/**
 * `nx make:schedule <Name>` — scaffold a scheduled task class.
 *
 * Generates:
 *   - src/schedule/tasks/<name>.task.ts
 *     — an @Injectable class with example @Cron / @Interval /
 *       @Timeout handlers
 *
 * Usage:
 *   nx make:schedule HourlyCleanup
 *   nx make:schedule DailyDigest --cron "@daily"
 *   nx make:schedule Heartbeat --interval 30000
 */

import { resolve } from "node:path";
import type { Command, CommandContext } from "../core/index.js";
import { logger, nameVariants, render, writeFile } from "../core/index.js";

const TASK_TEMPLATE = `
import { Inject, Injectable } from 'nexus';
import { Cron, Interval, Timeout, ScheduleService } from 'nexus/schedule';

/**
 * {{ name }} task — generated by \`nx make:schedule {{ name }}\`.
 *
 * Mark methods with \`@Cron\`, \`@Interval\`, or \`@Timeout\` and register
 * them at boot via \`scanForSchedulers(this, scheduleService)\`.
 */
@Injectable()
export class {{ name }}Task {
  constructor(@Inject(ScheduleService.TOKEN) private readonly schedule: ScheduleService) {}

  // TODO: add @Cron, @Interval, or @Timeout handlers below.

  // @Cron('0 * * * *')                          // every hour
  // async hourly() {
  //   this.schedule; // unused — remove if you don't need it
  // }

  // @Interval(60_000)                         // every minute
  // async tick() { /* ... */ }

  // @Timeout(5_000)                            // 5s after boot
  // async startup() { /* ... */ }
}

import { scanForSchedulers } from 'nexus/schedule';

/**
 * Bootstrap helper — call from main.ts to register every @Cron /
 * @Interval / @Timeout handler on this task class.
 */
export async function register{{ name }}(task: {{ name }}Task, schedule: ScheduleService) {
  return scanForSchedulers(task, schedule);
}
`.trimStart();

export const makeScheduleCommand: Command = {
	name: "make:schedule",
	aliases: ["msk", "make-schedule"],
	summary: "Scaffold a scheduled task class",
	description:
		"Generates an @Injectable task class with example @Cron / @Interval / @Timeout handlers under src/schedule/tasks/.",
	examples: [
		"nx make:schedule HourlyCleanup",
		"nx make:schedule DailyDigest",
	],
	async run(ctx: CommandContext): Promise<number> {
		const name = ctx.positional[0];
		if (!name) {
			logger.error("Usage: nx make:schedule <Name>");
			return 1;
		}

		const variants = nameVariants(name);
		const code = render(TASK_TEMPLATE, {
			name: variants.pascal,
			kebab: variants.kebab,
		});
		const out = resolve(
			ctx.cwd,
			"src/schedule/tasks",
			`${variants.kebab}.task.ts`,
		);

		if (writeFile(out, code, { skipIfExists: true })) {
			logger.success(`created ${out}`);
		} else {
			logger.warn(`skipped (exists): ${out}`);
		}

		logger.blank();
		logger.heading("Next steps");
		logger.info("1. Add @Cron / @Interval / @Timeout handlers to the class.");
		logger.info(`2. Import + register at boot:`);
		logger.info(`     scanForSchedulers(task, schedule)`);
		logger.info(`3. Don't forget to call \`schedule.start()\` to begin the tick.`);
		logger.blank();

		return 0;
	},
};

export default makeScheduleCommand;