/**
 * Session helper template — used by `nx make:session`.
 *
 * Context keys:
 *   name  — PascalCase class name (e.g. "Cart")
 *   kebab — kebab-case file name (e.g. "cart")
 */
export default `
import { Inject, Injectable } from '@nexusts/core';
import { SessionService } from '@nexusts/session';
import type { SessionRecord } from '@nexusts/session';

/**
 * {{ name }} session helper — generated by \`nx make:session {{ name }}\`.
 *
 * Wraps SessionService with typed accessors for the {{ name }} session's
 * data. Use from controllers / services.
 */
@Injectable()
export class {{ name }}Session {
  @Inject(SessionService.TOKEN) declare private readonly sessions: SessionService;

  /** Read the current session record (or null). */
  async getCurrent(sessionId: string | null | undefined) {
    if (!sessionId) return null;
    return this.sessions.read(sessionId);
  }

  /** Patch the {{ name }} session's data. */
  async update(sessionId: string, patch: {{ name }}DataPatch) {
    return this.sessions.update(sessionId, { dataPatch: patch });
  }

  /** Destroy the session (logout-everywhere equivalent). */
  async destroy(sessionId: string) {
    return this.sessions.destroy(sessionId, 'logout');
  }
}

/**
 * Typed payload for the {{ name }} session.
 *
 * TODO: define the fields below to match your feature.
 */
export interface {{ name }}Data {
  // userId?: string;
  // createdAt?: string;
}

export type {{ name }}DataPatch = Partial<{{ name }}Data>;
`.trimStart();
